### PR TITLE
 Use WebSphere Liberty helm chart to deploy stock-quote microservice

### PR DESCRIPTION
**Pull request by leochr**
- Use WebSphere Liberty helm chart to deploy stock-quote microservice
- Enable Monitoring

### CODE REVIEW

**Comment by leochr** [comment]
@jwalcorn  I noticed that the ingress of `trader` microservice was [changed](https://github.com/IBMStockTrader/trader/commit/41fb09e9b7b6846f283bca00245eff8587e73870#diff-16ec2fb13b0b13f11ed05365968c3b6d) recently (annotations and path). Will the ingress for `stock-quote` change similarly? if so, I can make those changes now.

**Comment by jwalcorn** [comment]
Actually, I was thinking of just removing the ingress for the downstream microservices.  I need it for `trader`, `tradr`, and `portfolio` (I have to expose Portfolio because the `tradr` client runs in the browser's JavaScript engine, so the call from it to Portfolio is from outside the Kube), but really shouldn't have it there for the other microservices, like `stock-quote`.  I think I'll still keep the node port though, for unit-test purposes

**Comment by leochr** [comment]
That makes sense. I'll update the PRs to remove the `ingress` parameter from rest of the values yaml.

**Comment by leochr** [comment]
@jwalcorn Removed `ingress` parameter from the values yaml for `stock-quote`, `notification-slack`, `notification-twitter` and `looper`. So all PRs are ready for review.

I didn't update the following microservices to use Liberty helm chart. Please let me know if you think they should be updated :
- `tradr` - it doesn't seem to be deployed on Liberty
- `loyalty-level` - marked as deprecated

**Comment by jwalcorn** [comment]
right, `tradr` is our one Node-based microservice (showing a little polyglot).  And yes, `loyalty-level` is deprecated and no longer used.

**Pull request merged**
